config/routes.rb
Rails.application.routes.draw do
  get 'user/admin_user'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  # action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      match '/destroy', action: :destroy, via: [:get, :delete], as: :destroy

      match 'favorite', action: :favorite, via: [:get, :post], as: :favorite
    end

    resources :favorites
    resources :comments, only: [:create, :destroy]
  end

  resources :activity_logs

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end
  
  match '/admin_user', to: 'users#admin_user', via: [:get, :post]
  
  resources :home do
    member do
      get '/history/', to: 'home#history', as: :history
      get '/user/', to: 'home#user', as: :user
      get '/favorite/', to: 'home#favorite', as: :favorite
    end
  end

  namespace :admin do

    get 'charts', to: 'home#charts', as: :charts
    root "home#index"
  end

  # Defines the root path route ("/")
  root "home#about"
end

app/views/shared/_footer.html.erb
<header class="text-center">
  oi
</header>

app/views/shared/_navbar.html.erb
<header>
    <a href="#" class="logo"><img src="https://i.imgur.com/e75G7zQ.png"></a>

    
    <%# Navbar Links_to %>
    <ul class="navbar">
        <li><a href="<%= root_path %>" class="active">Home</a></li>
        <% if user_signed_in? && current_user.admin? %>
          <li><a href="<%= admin_root_path %>" class="active">Admin Board</a></li>
        <% end %>
    </ul>

    
    <%# Icons %>
    <div class="icons">
      <div class="dropdown">
        <button class="#" type="#" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person"></i>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
            <li><%= link_to "Profile", user_home_path(current_user), class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><span class="dropdown-item">Balance: <%= number_to_currency(current_user.wallet.balance) %></span></li>
          <% else %>
            <li><%= link_to "New? Sign In", new_user_registration_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>

      <%# History Section %>
      <% if current_user.present? %>
        <a href="<%= history_home_path(current_user) %>"><i class="bi bi-bag-check"></i></a>
      <% else %>
        <a href="<%= new_user_session_path %>"><i class="bi bi-bag-check"></i></a>
      <% end %>
      
      <%# Favorite Section %>
      <% if current_user.present? %>
        <a href="<%= favorite_home_path(current_user) %>"><i class="bi bi-bag-heart"></i></a>
      <% else %>
        <a href="<%= new_user_session_path %>"><i class="bi bi-bag-heart"></i></a>
      <% end %>

      <%# Create a new Product Section %>
      <% if user_signed_in? %>
        <a href="<%= new_product_path %>"><i class="bi bi-box"></i></a>
      <% end %>

      <%# Portfolio Button for Jobs/etc %>
      <% unless user_signed_in? %>
        <a href="<%= admin_user_path %>" class="btn-home">Portfolio</a>
      <% end %>
    </div>
</header>