config/routes.rb
Rails.application.routes.draw do
  get 'user/admin_user'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  # action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      match '/destroy', action: :destroy, via: [:get, :delete], as: :destroy

      match 'favorite', action: :favorite, via: [:get, :post], as: :favorite
    end

    resources :favorites
    resources :comments, only: [:create, :destroy]
  end

  resources :activity_logs

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end
  
  match '/admin_user', to: 'users#admin_user', via: [:get, :post]
  
  resources :home do
    member do
      get '/history/', to: 'home#history', as: :history
      get '/user/', to: 'home#user', as: :user
      get '/favorite/', to: 'home#favorite', as: :favorite
    end
  end

  namespace :admin do

    get 'charts', to: 'home#charts', as: :charts
    root "home#index"
  end

  # Defines the root path route ("/")
  root "home#about"
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
    before_action :authenticate_user!

    def index
    end

    def charts
    end

    def pages
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def about
        @products = Product.all
    end

    def favorite
        @user = current_user
    end

    def user
        @user = current_user

    end

    def history
        @user = current_user
        @orders = @user.orders
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<section class="home">
  <div class="home-text">
    <h4>Simple Ecommerce in Rails 7</h4>
    <h1>Boost your sales with Ruby Shop!</h1>
    <a href="#product" class="btn-home">Explore Now</a>
  </div>

  <div class="home-img">
    <img src="https://i.imgur.com/LcXzAu7.png">
  </div>
</section>
<%# section feature %>
<section class="feature">
  <div class="middle-text">
    <h2>More features, have examples above, discover.</h2>
    <h3>Info-products, clothes, and everything else at <strong>Ruby Shop</strong></h3>
  </div>
  <br>
  <div class="feature-content">
    <div class="row">
      <div class="main-row">
        <div class="row-text">
          <h6>Explore the Products</h6>
          <a href="#" class="row-btn">Show me all</a>
          <div class="row-img">
            <img src="https://i.imgur.com/J6a1zwh.png">
            <img src="https://i.imgur.com/qOMFZ0B.png">
            <img src="https://i.imgur.com/nIKKbna.png">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="product" class="product">
  <div class="middle-text">
    <h2>Available<strong> products</strong></h2>
  </div>

<% @products.each_with_index do |product, index| %>
  <div>
    <div class="product-content" style="<%= 'display: none;' if index > 5 %>">
      <div class="box">
        <div class="box-img">
          <% if product.image.attached? %>
            <%= image_tag(product.image_webp, width: 100, heigth: 100 ) %>
          <% else %>
            <%= image_tag("https://i.imgur.com/jl1rTQL.png", width: 100, height: 100) %>
          <% end %>
        </div>
        <h3>Owner: <%= product.user.email %></h3>
        <h3><%= product.name %></h3>
        <h4><%= product.description %></h4>
        <div class="inbox">
          <div>
            <a href="<%= product_path(product) %>" class="price"><%= number_to_currency(product.price, unit: 'R$', separator: ',', delimiter: '.') %></a>
            <% if product && current_user == product.user %>
              <%= link_to "Edit", edit_product_path(product), class: "edit" %>
              <%= link_to "Show", product_path(product), class: "edit" %>
            <% end %>
            <% if current_user.present? && (current_user.admin? || (product.present? && current_user == product.user)) %>
              <%= link_to "Delete?", destroy_product_path(product), class: "edit" %>
            <% end %>
          </div>
          <div class="rating">
            <% (1..5).each do |i| %>
              <a href="#"><i class="bi bi-star-fill"></i></a>
            <% end %>
          </div>
        </div>
        <%= link_to favorite_product_path(product), method: :post, remote: true do %>
          <div class="heart">
            <i class="bi bi-suit-heart"></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <% if index == 5 && @products.length > 6 %>
    <div class="show-more">
      <button class="btn-home" onclick="showMoreProducts()"> > </button>
    </div>
  <% end %>
<% end %>
</section>

<script>
  function showMoreProducts() {
    var showMoreButton = document.querySelector('.show-more button');
    var buttonText = showMoreButton.textContent;

    if (buttonText == " > ") {
      document.querySelectorAll('.product-content').forEach(function(el) {
        el.style.display = 'block';
      });
      showMoreButton.textContent = " < ";
    } else {
      document.querySelectorAll('.product-content').forEach(function(el, index) {
        if (index > 5) {
          el.style.display = 'none';
        }
      });
      showMoreButton.textContent = " > ";
    }
  }
</script>

<%# contact %>
<section class="contact">
  <div class="main-contact">
    <div class="contact-content">
      <h5>Getting started</h5>
      <li><a href="#">Release Notes</a></li>
      <li><a href="#">Dark Mode</a></li>
      <li><a href="#">Browser Support</a></li>
    </div>

    <div class="contact-content">
      <h5>Explore</h5>
      <li><a href="#">Prototyping</a></li>
      <li><a href="#">Design systems</a></li>
      <li><a href="#">Pricing</a></li>
    </div>

    <div class="contact-content">
      <h5>Resources</h5>
      <li><a href="#">Best practices</a></li>
      <li><a href="#">Support</a></li>
      <li><a href="#">Developers</a></li>
    </div>

    <div class="contact-content">
      <h5>Community</h5>
      <li><a href="#"><i class="bi bi-shop"></i></i> Repository</a></li>
      <li><a href="#"><i class="bi bi-github"></i> My GitHub</a></li>
      <li><a href="#"><i class="bi bi-linkedin"></i> Linkedin</a></li>
    </div>
  </div>
</section>

<div class="end-text">
  <p>© 2024 Ruby Shop</p>
</div>

app/views/home/favorite.html.erb
<br>
<br>
<br>
<br>
<div class="text-center">
  <strong>Your Favorites</strong>
</div>
<br>
<br>
<div class="text-center">
  <% @user.favorited_products.each do |product| %>
    <p><strong>Name</strong>: <%= product.name %> <%= link_to "See Product", product_path(product) %> <%= link_to "Remove Favorite", favorite_product_path(product), method: :delete, remote: true %></p>
  <% end %>
</div>

app/views/home/history.html.erb
<br>
<br>
<br>
<br>
<div class="text-center">
  <strong>Your Orders</strong>
</div>
<br>
<br>
<div class="text-center">
  <%# if the user HAVE orders.  %>
    <% if @orders.any? %>
      <% order_number = 1 %>
      <% @orders.order(id: :asc).each do |order| %>
        <p><strong>Order: </strong> <%= order_number %></p>
  
      <ul class="text-center">
        <% order.order_items.each do |order_item| %>
          <strong>Name</strong>: <li><%= order_item.product.name %></li>
          <strong>Quantity</strong>: <%= order_item.quantity %>
        <% end %>
      </ul>

      <% order_number += 1 %>
      <% end %>
    <% else %>
        <p class="text-center">Orders not found.</p>
    <% end %>
</div>

app/views/home/user.html.erb
<br>
<br>
<br>
<br>
<div class="text-center fs-6">
  <% if user_signed_in? %>
    <%= link_to "Edit", edit_user_registration_path %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
  <% else %>
    <%= render 'devise/sessions/new' %>
  <% end %>
</div>